#!/usr/bin/env bash
# Fixes the nginx listening port and reloads the nginx master process

# Fix the nginx listening port
echo -e "sed -iE 's/listen 8080/listen 80/g' /etc/nginx/sites-enabled/default\
sudo sed -i 's/listen \[::\]:8080/listen \[::\]:80/g' /etc/nginx/sites-enabled/default\n
pgrep nginx -o > /run/nginx.pid\nnginx -s reload\necho''> /run/nginx.pid" | bash

# Reload the nginx master process
sudo service nginx restart
